double TABLE_VERTICAL_PADDING = 6;
const double STANDART_BUTTON_HEIGHT = 50;
const double STANDART_BUTTON_WIDTH = 300;

const String YOUR_PERSONAL_ACCESS_TOKEN =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY3NDY1ODE4MSwiZXhwIjoxNzA2MTk0MTgxfQ.w4z05pImThEbE8xyP4-IlkTJuvhzHBIqEkr1hynp3_w';
